### PR TITLE
Create a button to close the help modal

### PR DESCRIPTION
**Pull request by Kcchouette**
1. normally you do a modal, not a panel (and so you don't do a trick using javascript onclick) because bootstrap do that
1. the git code is not the same than the one on the website (`ui-draggable-handle` is not available in the class of the git one)
1. it would be good to create README to explain where we can find the project, how we can use it at home (because I've not tested the PHP code, I can't launch without database MYSQL, and I don't know how to create that DB)

Cheers

### CODE REVIEW

**Comment by farlistener** [comment]
why do you want this panel to be closed ?

**Comment by Kcchouette** [comment]
Because it's not very beautiful :/

screenshot

**Comment by farlistener** [comment]
It's because you have a "small" screen, a work around the integration is needed but this is not a "modal" window

**Comment by Kcchouette** [comment]
Ah, ok.

I didn't understand that when I've seen that on the website.
You can close the PR if you want to reject it.

**Pull request closed without merging**
